name: Clang

on: [push, pull_request]

jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    env:
      cc: clang
      cxx: clang++
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: |
          mkdir build
          cmake -DCMAKE_CXX_FLAGS="-D__clang__" -S test -B build
      - name: Build
        run: cmake --build build --config Release
      - name: Run
        run: ./build/CppUtilTest
