name: Gcc

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.config.name }}
    runs-on: "ubuntu-latest"
    env:
      cc: gcc
      cxx: g++
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: Address sanitize, sanitizer: address }
          - { name: Thread sanitizer, sanitizer: thread }
          - { name: Undefined behaiver sanitizer, sanitizer: undefined }
    steps:
      - uses: actions/checkout@v2
      - name: Install gcc
        run: |
          sudo apt update
          sudo apt-get purge gcc
          sudo apt install gcc-11 g++-11
      - name: Configure
        run: |
          mkdir build
          cmake -DCMAKE_CXX_FLAGS="-fsanitize=${{ matrix.config.sanitizer }}" -S test -B build
      - name: Build
        run: cmake --build build --config Debug
      - name: Run
        run: ./build/CppUtilTest
