name: Msvc

on: [push, pull_request]

jobs:
  test:
    name: "Test"
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: |
          mkdir build
          cmake -S test -B build
      - name: Build
        run: cmake --build build --config Release
      - name: Run
        run: ./build/Release/CppUtilTest.exe
